/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ballcupgame;

import java.util.Random;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author glaba
 */
public class BasicGameGUI extends javax.swing.JFrame {

    /**
     * Creates new form BasicGameGUI
     */
    static String user;
    static int difficulty;
    int score;
    Main cups;

    public BasicGameGUI() {
        initComponents();
    }

    public BasicGameGUI(String username, int difficulty) {

        initComponents();
        score = 0;

        this.user = username;
        jTextFieldUserName.setText(user);
        cups = new Main(new Random());
        cups.shuffle();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCup1 = new javax.swing.JButton();
        jButtonCup2 = new javax.swing.JButton();
        jButtonCup3 = new javax.swing.JButton();
        jTextFieldUserName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCup1.setText("Cup 1");
        jButtonCup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCup1ActionPerformed(evt);
            }
        });

        jButtonCup2.setText("Cup 2");
        jButtonCup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCup2ActionPerformed(evt);
            }
        });

        jButtonCup3.setText("Cup 3");
        jButtonCup3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCup3ActionPerformed(evt);
            }
        });

        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCup1))
                .addGap(18, 18, 18)
                .addComponent(jButtonCup2)
                .addGap(18, 18, 18)
                .addComponent(jButtonCup3)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCup1)
                    .addComponent(jButtonCup2)
                    .addComponent(jButtonCup3))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCup2ActionPerformed
        if (cups.getCup(2).checkForBall() == true) {
            score += 1;
            cups.shuffle();
        } else {
            JOptionPane.showMessageDialog(rootPane, "YOU FAILED YOU LOSER");
            setVisible(false);

        }    }//GEN-LAST:event_jButtonCup2ActionPerformed

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jButtonCup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCup1ActionPerformed
        if (cups.getCup(1).checkForBall() == true) {
            score += 1;
            cups.shuffle();
        } else {
            JOptionPane.showMessageDialog(rootPane, "YOU FAILED YOU LOSER");
            setVisible(false);

        }

    }//GEN-LAST:event_jButtonCup1ActionPerformed

    private void jButtonCup3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCup3ActionPerformed
        if (cups.getCup(3).checkForBall() == true) {
            score += 1;
            cups.shuffle();
        } else {
            JOptionPane.showMessageDialog(rootPane, "YOU FAILED YOU LOSER");
            setVisible(false);

        }    }//GEN-LAST:event_jButtonCup3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BasicGameGUI(user, difficulty).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCup1;
    private javax.swing.JButton jButtonCup2;
    private javax.swing.JButton jButtonCup3;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
